[package]
name = "tokens"
version = "0.1.0"
authors = ["Ole Herman Schumacher Elgesem <ole.elgesem@northern.tech>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
